version: "3.9"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma_root_password
      MYSQL_DATABASE: prisma_db
      MYSQL_USER: prisma_user
      MYSQL_PASSWORD: prisma_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
